export enum DrugForm {
    TABLET = "TAB",
    CAPSULE = "CAP",
    SYRUP = "SYP",
    SUSPENSION = "SUSP",
    INJECTION = "INJ",
    CREAM = "CRM",
    OINTMENT = "OINT",
    GEL = "GEL",
    SOLUTION = "SOL",
    DROPS = "DROPS",
    LOZENGES = "LOZ",
    POWDER = "PWD",
    SUPPOSITORY = "SUPP",
    SPRAY = "SPRAY",
    TRANSDERMAL_PATCH = "PATCH",
    INHALER = "INHL",
    SHAMPOO = "SHAM",
    MEDICATED_SOAP = "SOAP",
    FOAM = "FOAM",
    MOUTHWASH = "MOUTH",
    TEST_STRIP = "STRIP",
    OTHER = "OTH"
};