package org.cms.Users.Controllers;

import org.cms.Users.Models.User;
import org.cms.Users.Repositories.UserRepository;
import org.cms.Users.Services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController // means the class is a controller
@RequestMapping("/api/v1/users") // means URL's start with /api/v1/users (after application path)
public class UserController {
    @Autowired // means to get the bean called userRepository
        // which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private UserService userService;

    @PostMapping(path = "/create")
    public @ResponseBody User createUser(@RequestBody User user) {
        return userService.create(user);
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

    @DeleteMapping(path = "/delete")
    public @ResponseBody User deleteUser(@RequestParam int userId) {
        return userService.delete(userId);
    }

    @PutMapping(path = "/update")
    public @ResponseBody User updateUser(@RequestBody User user, @RequestParam int userId) {
        return userService.update(user, userId);
    }
}
